-- H2 Database Script (Full - Including Sequence Creation)

CREATE SEQUENCE IF NOT EXISTS USERS_ID_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS PROJECT_ID_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SPRINT_ID_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS TASK_ID_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS ACTIVITY_ID_SEQ START WITH 1 INCREMENT BY 1;


CREATE TABLE IF NOT EXISTS USERS
(
    ID           BIGINT DEFAULT NEXT VALUE FOR USERS_ID_SEQ PRIMARY KEY,
    EMAIL        VARCHAR(255),
    PASSWORD     VARCHAR(255),
    FIRST_NAME   VARCHAR(255),
    LAST_NAME    VARCHAR(255),
    DISPLAY_NAME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS PROJECT
(
    ID          BIGINT DEFAULT NEXT VALUE FOR PROJECT_ID_SEQ PRIMARY KEY,
    CODE        VARCHAR(255),
    TITLE       VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    TYPE_CODE   VARCHAR(255),
    PARENT_ID   BIGINT
);

CREATE TABLE IF NOT EXISTS SPRINT
(
    ID          BIGINT DEFAULT NEXT VALUE FOR SPRINT_ID_SEQ PRIMARY KEY,
    STATUS_CODE VARCHAR(255),
    STARTPOINT  TIMESTAMP,
    ENDPOINT    TIMESTAMP,
    CODE        VARCHAR(255),
    PROJECT_ID  BIGINT
);

CREATE TABLE IF NOT EXISTS TASK
(
    ID          BIGINT DEFAULT NEXT VALUE FOR TASK_ID_SEQ PRIMARY KEY,
    TITLE       VARCHAR(255),
    TYPE_CODE   VARCHAR(255),
    STATUS_CODE VARCHAR(255),
    PROJECT_ID  BIGINT,
    SPRINT_ID   BIGINT,
    STARTPOINT  TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ACTIVITY
(
    ID            BIGINT DEFAULT NEXT VALUE FOR ACTIVITY_ID_SEQ PRIMARY KEY,
    AUTHOR_ID     BIGINT,
    TASK_ID       BIGINT,
    UPDATED       TIMESTAMP,
    COMMENT       VARCHAR(255),
    TITLE         VARCHAR(255),
    DESCRIPTION   VARCHAR(255),
    ESTIMATE      INTEGER,
    TYPE_CODE     VARCHAR(255),
    STATUS_CODE   VARCHAR(255),
    PRIORITY_CODE VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS USER_ROLE
(
    USER_ID BIGINT,
    ROLE    INTEGER
);

CREATE TABLE IF NOT EXISTS PROFILE
(
    ID                 BIGINT PRIMARY KEY,
    LAST_FAILED_LOGIN  TIMESTAMP,
    LAST_LOGIN         TIMESTAMP,
    MAIL_NOTIFICATIONS INTEGER
);

CREATE TABLE IF NOT EXISTS USERS
(
    ID           BIGINT DEFAULT NEXT VALUE FOR USERS_ID_SEQ PRIMARY KEY,
    EMAIL        VARCHAR(255),
    PASSWORD     VARCHAR(255),
    FIRST_NAME   VARCHAR(255),
    LAST_NAME    VARCHAR(255),
    DISPLAY_NAME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS PROJECT
(
    ID          BIGINT DEFAULT NEXT VALUE FOR PROJECT_ID_SEQ PRIMARY KEY,
    CODE        VARCHAR(255),
    TITLE       VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    TYPE_CODE   VARCHAR(255),
    PARENT_ID   BIGINT
);

CREATE TABLE IF NOT EXISTS SPRINT
(
    ID          BIGINT DEFAULT NEXT VALUE FOR SPRINT_ID_SEQ PRIMARY KEY,
    STATUS_CODE VARCHAR(255),
    STARTPOINT  TIMESTAMP,
    ENDPOINT    TIMESTAMP,
    CODE        VARCHAR(255),
    PROJECT_ID  BIGINT
);

CREATE TABLE IF NOT EXISTS TASK
(
    ID          BIGINT DEFAULT NEXT VALUE FOR TASK_ID_SEQ PRIMARY KEY,
    TITLE       VARCHAR(255),
    TYPE_CODE   VARCHAR(255),
    STATUS_CODE VARCHAR(255),
    PROJECT_ID  BIGINT,
    SPRINT_ID   BIGINT,
    STARTPOINT  TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ACTIVITY
(
    ID            BIGINT DEFAULT NEXT VALUE FOR ACTIVITY_ID_SEQ PRIMARY KEY,
    AUTHOR_ID     BIGINT,
    TASK_ID       BIGINT,
    UPDATED       TIMESTAMP,
    COMMENT       VARCHAR(255),
    TITLE         VARCHAR(255),
    DESCRIPTION   VARCHAR(255),
    ESTIMATE      INTEGER,
    TYPE_CODE     VARCHAR(255),
    STATUS_CODE   VARCHAR(255),
    PRIORITY_CODE VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS USER_ROLE
(
    USER_ID BIGINT,
    ROLE    INTEGER
);

CREATE TABLE IF NOT EXISTS PROFILE
(
    ID                 BIGINT PRIMARY KEY,
    LAST_FAILED_LOGIN  TIMESTAMP,
    LAST_LOGIN         TIMESTAMP,
    MAIL_NOTIFICATIONS INTEGER
);

CREATE TABLE IF NOT EXISTS CONTACT
(
    ID            BIGINT,
    CODE          VARCHAR(255),
    CONTACT_VALUE VARCHAR(255) -- ИЗМЕНЕНО: VALUE -> CONTACT_VALUE
);

CREATE TABLE IF NOT EXISTS USER_BELONG
(
    OBJECT_ID      BIGINT,
    OBJECT_TYPE    INTEGER,
    USER_ID        BIGINT,
    USER_TYPE_CODE VARCHAR(255),
    STARTPOINT     TIMESTAMP,
    ENDPOINT       TIMESTAMP
);

DELETE
FROM USER_ROLE;
DELETE
FROM CONTACT;
DELETE
FROM PROFILE;

DELETE
FROM ACTIVITY;
ALTER SEQUENCE ACTIVITY_ID_SEQ RESTART WITH 1;
DELETE
FROM TASK;
ALTER SEQUENCE TASK_ID_SEQ RESTART WITH 1;
DELETE
FROM SPRINT;
ALTER SEQUENCE SPRINT_ID_SEQ RESTART WITH 1;
DELETE
FROM PROJECT;
ALTER SEQUENCE PROJECT_ID_SEQ RESTART WITH 1;

DELETE
FROM USERS;
ALTER SEQUENCE USERS_ID_SEQ RESTART WITH 1;

INSERT INTO USERS (EMAIL, PASSWORD, FIRST_NAME, LAST_NAME, DISPLAY_NAME)
VALUES ('user@gmail.com', '{noop}password', 'userFirstName', 'userLastName', 'userDisplayName'),
       ('admin@gmail.com', '{noop}admin', 'adminFirstName', 'adminLastName', 'adminDisplayName'),
       ('guest@gmail.com', '{noop}guest', 'guestFirstName', 'guestLastName', 'guestDisplayName'),
       ('manager@gmail.com', '{noop}manager', 'managerFirstName', 'managerLastName', 'managerDisplayName');

-- 0 DEV
-- 1 ADMIN
-- 2 MANAGER

INSERT INTO USER_ROLE (USER_ID, ROLE)
VALUES (1, 0),
       (2, 0),
       (2, 1),
       (4, 2);

INSERT INTO PROFILE (ID, LAST_FAILED_LOGIN, LAST_LOGIN, MAIL_NOTIFICATIONS)
VALUES (1, NULL, NULL, 49),
       (2, NULL, NULL, 14);

INSERT INTO CONTACT (ID, CODE, CONTACT_VALUE)
VALUES (1, 'skype', 'userSkype'),
       (1, 'mobile', '+01234567890'),
       (1, 'website', 'user.com'),
       (2, 'github', 'adminGitHub'),
       (2, 'tg', 'adminTg'),
       (2, 'vk', 'adminVk');


INSERT INTO PROJECT (code, title, description, type_code, parent_id)
VALUES ('PR1', 'PROJECT-1', 'test project 1', 'task_tracker', NULL),
       ('PR2', 'PROJECT-2', 'test project 2', 'task_tracker', 1);

INSERT INTO SPRINT (status_code, startpoint, endpoint, code, project_id)
VALUES ('finished', '2023-05-01 08:05:10', '2023-05-07 17:10:01', 'SP-1.001', 1),
       ('active', '2023-05-01 08:06:00', NULL, 'SP-1.002', 1),
       ('active', '2023-05-01 08:07:00', NULL, 'SP-1.003', 1),
       ('planning', '2023-05-01 08:08:00', NULL, 'SP-1.004', 1),
       ('active', '2023-05-10 08:06:00', NULL, 'SP-2.001', 2),
       ('planning', '2023-05-10 08:07:00', NULL, 'SP-2.002', 2),
       ('planning', '2023-05-10 08:08:00', NULL, 'SP-2.003', 2);

INSERT INTO TASK (TITLE, TYPE_CODE, STATUS_CODE, PROJECT_ID, SPRINT_ID, STARTPOINT)
VALUES ('Data', 'epic', 'in_progress', 1, 1, '2023-05-15 09:05:10'),
       ('Trees', 'epic', 'in_progress', 1, 1, '2023-05-15 12:05:10'),
       ('task-3', 'task', 'ready_for_test', 2, 5, '2023-06-14 09:28:10'),
       ('task-4', 'task', 'ready_for_review', 2, 5, '2023-06-14 09:28:10'),
       ('task-5', 'task', 'todo', 2, 5, '2023-06-14 09:28:10'),
       ('task-6', 'task', 'done', 2, 5, '2023-06-14 09:28:10'),
       ('task-7', 'task', 'canceled', 2, 5, '2023-06-14 09:28:10');


INSERT INTO ACTIVITY(AUTHOR_ID, TASK_ID, UPDATED, COMMENT, TITLE, DESCRIPTION, ESTIMATE, TYPE_CODE, STATUS_CODE,
                     PRIORITY_CODE)
VALUES (1, 1, '2023-05-15 09:05:10', NULL, 'Data', NULL, 3, 'epic', 'in_progress', 'low'),
       (2, 1, '2023-05-15 12:25:10', NULL, 'Data', NULL, NULL, NULL, NULL, 'normal'),
       (1, 1, '2023-05-15 14:05:10', NULL, 'Data', NULL, 4, NULL, NULL, NULL),
       (1, 2, '2023-05-15 12:05:10', NULL, 'Trees', 'Trees desc', 4, 'epic', 'in_progress', 'normal');

INSERT INTO USER_BELONG (OBJECT_ID, OBJECT_TYPE, USER_ID, USER_TYPE_CODE, STARTPOINT, ENDPOINT)
VALUES (1, 2, 2, 'task_developer', '2023-06-14 08:35:10', '2023-06-14 08:55:00'),
       (1, 2, 2, 'task_reviewer', '2023-06-14 09:35:10', NULL),
       (1, 2, 1, 'task_developer', '2023-06-12 11:40:00', '2023-06-12 12:35:00'),
       (1, 2, 1, 'task_developer', '2023-06-13 12:35:00', NULL),
       (1, 2, 1, 'task_tester', '2023-06-14 15:20:00', NULL),
       (2, 2, 2, 'task_developer', '2023-06-08 07:10:00', NULL),
       (2, 2, 1, 'task_developer', '2023-06-09 14:48:00', NULL),
       (2, 2, 1, 'task_tester', '2023-06-10 16:37:00', NULL);
